version: '3.6'

x-build-args: &build_args
  INSTALL_NODE_VERSION: 16 

x-default-volumes: &default_volumes
  volumes:
    - '.:/usr/src/'
    - '/usr/src/node_modules'
    - '/usr/src/.next'

services:
  blockhead:
    container_name: blockhead
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "blockhead"
    ports:
      - "3000:3000"
    <<: *default_volumes
